server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =========================
# GEMINI AI
# =========================
gemini.api.key=${GOOGLE_API_KEY}
gemini.model=gemini-2.5-flash
gemini.fallback.model=gemini-2.5-flash-lite

# =========================
# MSG91
# =========================
msg91.authkey=${MSG91_AUTH_KEY:}
msg91.templateId=${MSG91_TEMPLATE_ID:}
msg91.sender=${MSG91_SENDER:SMSIND}

# =========================
# TWILIO
# =========================
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.from.number=${TWILIO_FROM_NUMBER}

# =========================
# PHONEPE
# =========================
phonepe.env=SANDBOX

phonepe.merchant-id=${PHONEPE_MERCHANT_ID:}
phonepe.client-id=${PHONEPE_CLIENT_ID:}
phonepe.client-secret=${PHONEPE_CLIENT_SECRET:}

phonepe.client-version=1

phonepe.base-url=https://api-preprod.phonepe.com/apis/pg-sandbox

phonepe.redirect-url=rahulhardware://payment-result

phonepe.auth-url=https://api-preprod.phonepe.com/apis/pg-sandbox/v1/oauth/token

phonepe.create-order-url=https://api-preprod.phonepe.com/apis/pg-sandbox/checkout/v2/sdk/order

phonepe.status-url=https://api-preprod.phonepe.com/apis/pg-sandbox/checkout/v2/order

# =========================
# WHATSAPP CLOUD API
# =========================
whatsapp.api-url=https://graph.facebook.com/v20.0
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.template-name=hello_world
whatsapp.template-language=en_US
whatsapp.otp-expiry-minutes=5